---
- hosts: wordpress
  become: true 
  tasks:
    - name: Install EPEL Repository
      yum: 
        name: epel-release
        state: present
      
    - name: Install rsync
      package:
        name: rsync
        state: present

    - name: Set up firewall rules
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - ssh
        - http
        - https

    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
    
    - name: Install nginx
      package:
        name: nginx
        state: present
    
    - name: Copy nginx configuration file
      copy: 
        src: ./wp_setup_files/nginx.conf
        dest: /etc/nginx/nginx.conf
    
    - name: Start and enable nginx
      service: 
        name: nginx
        state: restarted
        enabled: yes

    - name: Install php
      package:
        name: "{{ item }}"
      with_items:
        - php
        - php-fpm
        - php-mysql

    - name: Copy php configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "./wp_setup_files/php.ini", dest: "/etc/php.ini"}
        - { src: "./wp_setup_files/www.conf", dest: "/etc/php-fpm.d/www.conf"}
        
    - name: Restart and enable php-fpm
      service:
        name: php-fpm
        state: restarted
        enabled: yes

    - name: Install mariadb
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - mariadb-server
        - mariadb

    - name: Restart and enable mariadb
      service: 
        name: mariadb
        state: restarted
        enabled: yes

    - name: Transfer mariadb config files
      copy:
        src:  ./wp_setup_files/mariadb_config
        dest: /
      
    - name: Set initial mariadb configuration
      script: ./wp_setup_files/wp_mariadb.sh

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted

    - name: Remove temp config files
      file:
        path: /mariadb_config
        state: absent

    - name: Download and unpack wordpress archive
      unarchive:
        src: http://wordpress.org/latest.tar.gz
        dest: /
        remote_src: yes

    - name: Set up wordpress
      copy:
        src: ./wp_setup_files/wp-config.php
        dest: /wordpress/wp-config.php

    - name: Transfer wordpress to nginx folder
      command: rsync -avP /wordpress/ /usr/share/nginx/html

    - name: Clean up temporary wordpress folder
      file:
        path: /wordpress
        state: absent

    - name: Change ownership of wordpress source
      file:
        path: /usr/share/nginx/html
        state: directory
        owner: admin
        group: nginx
        recurse: yes

    - name: Create and setup ownership of uploads folder
      file:
        path: /usr/share/nginx/html/wp-content/uploads
        state: directory
        owner: admin
        recurse: yes
        group: nginx
        mode: g+w    
... 